### ISSUE TITLE
Missing a sendMessage for remainingTime/elapsedTime for cooldownTick

### ISSUE THREAD

**Issue by mrflamegoat** [SupportClass/lfg-hypetrain#3]
Wasn't getting an update tick from the cool down, and it turns out that there's no sendmessage for the cooldownTick for the timer update.

Something like this in Train.prototype.tickCooldown I'm assuming:

`nodecg.sendMessage('cooldownTick', [{"remainingTime": remainingTime, "elapsedTime": elapsedTime}]);`

This is how I fixed it, but I could be missing something.

**Comment by Lange** [comment]
Good catch, I must have inadvertently removed it ages ago during some refactor. As you may have been able to tell by the README, I hadn't updated parts of this bundle in a very long time. I just cleaned things up a bit and released [v2.0.1](https://github.com/SupportClass/lfg-hypetrain/releases/tag/v2.0.1).
